algoritmo "Verificando se a pessoa pode dirigir"
// Autor : Vitor Rodrigues Santos
// Data : 13/04/2026

//As variáveis serão escritas abaixo
var
idade: real

inicio

      escreva("Digite quantos anos você tem: ")
      leia (idade)

se idade >= 18 entao

   limpatela
   
   escreva("Você possui ", idade, " anos, logo, pode dirigir")
   
senao
     limpatela

     escreva("Você possui ", idade, " anos, logo, pode dirigir")
     
fimse

fimalgoritmo
